In [43]:
import numpy as np
CURVE_CENTER=80
grades=np.array([90,80,90,70,78,45,67])
def curve(grades):
    average=grades.mean()
    print(average)
    change=CURVE_CENTER-average
    new_grades=grades+change
  
    return np.clip(new_grades,grades,100)
curve(grades)

74.28571428571429


array([95.71428571, 85.71428571, 95.71428571, 75.71428571, 83.71428571,
       50.71428571, 72.71428571])

In [22]:
grades.shape



(7,)

In [41]:
numbers=np.linspace(5,50,24,dtype=int)
numbers

array([ 5,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40, 42, 44, 46, 48, 50])

In [46]:
mask=numbers%4==0
mask

array([False, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [47]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])